### ISSUE TITLE
debug.apk在安卓手机上有问题

### ISSUE THREAD

**Issue by kali20gakki** [mindcont/RubikRobot#5]
安卓4.2的手机 解析包出现问题
其他安卓手机都存在一进app就闪退的问题

**Comment by mindcont** [comment]
@kali20gakki 

你好，很高兴你能关注这个项目。apk开机欢迎界面引入了一个组件需要andriod 4.4 (api 19) 以上的版本才能运行。

排除网络原因
```java
MD5 382a39857958e0942b851920cb4c12ee  app-debug.apk
sha1sum 92f2f87d53c992be42633e8de8ca330ffa4d1b41  app-debug.apk
```

先睹为快

![image](http://static.mindcont.com/blog/images/coding/android/S70822-143459.jpg)

**Comment by kali20gakki** [comment]
你好，我又试过当今的3款主流机（安卓6.01），均存在闪退情况。即使我提前把摄像头，蓝牙权限给debug.apk,依然存在闪退情况，比较好的是进入引导界面后点击立即体验后闪退，其他都是直接打开app就闪退。我又重新打包了apk，还是存在以上问题。
我才接触安卓，有什么不对还请多多指教。

**Comment by mindcont** [comment]
将手机连接电脑，打开android studio ，点击运行调试，选择你的手机，观察控制台 log 信息或粘贴出来

如下图所示

> ![](http://www.cs.dartmouth.edu/~campbell/cs65/lecture10/images/debug.png)
>
>
> _----图片来源于网络_

我对安卓也研究不深，初学的话，建议运行 官方的例子程序或优秀的开源作品，如 

- [UniversalMusicPlayer](https://github.com/googlesamples/android-UniversalMusicPlayer) 
- [高仿微信](https://github.com/motianhuo/wechat)
- [四次元](https://github.com/qii/weiciyuan) 

进行学习，阅读优秀的代码，可以更好的入门，少走弯路。

**Comment by kali20gakki** [comment]
```
08-23 18:40:03.791 29435-29435/com.dreamwalker.rubikrobot E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.dreamwalker.rubikrobot, PID: 29435
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dreamwalker.rubikrobot/com.dreamwalker.rubikrobot.ui.WelcomeGuideActivity}: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class <unknown>
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2449)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
    at android.app.ActivityThread.access$1000(ActivityThread.java:153)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:5528)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:740)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630)
 Caused by: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class <unknown>
    at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
    at com.dreamwalker.rubikrobot.ui.WelcomeGuideActivity.onCreate(WelcomeGuideActivity.java:45)
    at android.app.Activity.performCreate(Activity.java:6303)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509) 
    at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:154) 
    at android.app.ActivityThread.main(ActivityThread.java:5528) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:740) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630) 
 Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class <unknown>
    at android.view.LayoutInflater.createView(LayoutInflater.java:649)
    at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:698)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:766)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:839)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
    at com.dreamwalker.rubikrobot.ui.WelcomeGuideActivity.onCreate(WelcomeGuideActivity.java:45) 
    at android.app.Activity.performCreate(Activity.java:6303) 
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402) 
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509) 
    at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:154) 
    at android.app.ActivityThread.main(ActivityThread.java:5528) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:740) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630) 
 Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.newInstance(Native Method)
    at android.view.LayoutInflater.createView(LayoutInflater.java:623)
    at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:698) 
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:766) 
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708) 
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:839) 
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:519) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
    at com.dreamwalker.rubikrobot.ui.WelcomeGuideActivity.onCreate(WelcomeGuideActivity.java:45) 
    at android.app.Activity.performCreate(Activity.java:6303) 
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402) 
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509) 
    at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:154) 
    at android.app.ActivityThread.main(ActivityThread.java:5528) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:740) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630) 
 Caused by: java.lang.OutOfMemoryError: Failed to allocate a 35926012 byte allocation with 10299112 free bytes and 9MB until OOM
    at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
    at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
    at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:613)
    at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:446)
    at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1080)
    at android.content.res.Resources.createFromResourceStream(Resources.java:2952)
    at android.content.res.Resources.loadDrawableForCookie(Resources.java:2684)
    at android.content.res.Resources.loadDrawable(Resources.java:2580)
    at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:387)
    at android.content.res.TypedArray.getDrawable(TypedArray.java:872)
    at android.widget.ImageView.<init>(ImageView.java:152)
    at android.widget.ImageView.<init>(ImageView.java:140)
    at android.widget.ImageView.<init>(ImageView.java:136)
    at java.lang.reflect.Constructor.newInstance(Native Method) 
    at android.view.LayoutInflater.createView(LayoutInflater.java:623) 
    at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:698) 
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:766) 
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708) 
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:839) 
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:519) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
    at com.dreamwalker.rubikrobot.ui.WelcomeGuideActivity.onCreate(WelcomeGuideActivity.java:45) 
    at android.app.Activity.performCreate(Activity.java:6303) 
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402) 
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509) 
    at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:154) 
    at android.app.ActivityThread.main(ActivityThread.java:5528) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:740) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630) 
```

**Comment by mindcont** [comment]
@kali20gakki 

貌似app欢迎界面的资源引用问题，在AndroidManifest.xml 屏蔽欢迎界面的引入

change `/app/RubikRobot/app/src/main/AndroidManifest.xml` [Line 27-43](https://github.com/mindcont/RubikRobot/blob/master/app/RubikRobot/app/src/main/AndroidManifest.xml#L27-L43)

```xml
       <activity
            android:name="com.dreamwalker.rubikrobot.ui.WelcomeActivity"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.DayNight.NoActionBar">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <activity
            android:name="com.dreamwalker.rubikrobot.MainActivity"
            android:screenOrientation="portrait">

        </activity>
```
to
```xml
  <activity
            android:name="com.dreamwalker.rubikrobot.MainActivity"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.DayNight.NoActionBar">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
```
然后编译，调试，试试

**Comment by kali20gakki** [comment]
setParameters方法出错了
log:  java.lang.RuntimeException: setParameters failed
	at android.hardware.Camera.native_setParameters(Native Method)
	at android.hardware.Camera.setParameters(Camera.java:2011)
	at com.dreamwalker.rubikrobot.MainActivity$SurfaceCallback.surfaceChanged(MainActivity.java:617)
	at android.view.SurfaceView.updateWindow(SurfaceView.java:608)
	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:179)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2082)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6050)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
	at android.view.Choreographer.doCallbacks(Choreographer.java:672)
	at android.view.Choreographer.doFrame(Choreographer.java:608)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
	at android.os.Handler.handleCallback(Handler.java:742)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:5528)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:740)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630)

**Comment by mindcont** [comment]
@kali20gakki  抱歉，最近比较忙，未能及时回复

这是一个相机已知错误，目前仍未解决。我的魅族手机上未报这个错误，而我同学小米的手机就报了这个错误。如果你找到了通用的解决办法，欢迎push~

> [Android调用camera错误setParameters failed深层解析](http://blog.csdn.net/stoppig/article/details/40591973)

**Comment by kali20gakki** [comment]
@mindcont 在网上查找了一些原因 可能是MIUI对camera深度定制 导致setParameters不能用

但是仔细查看代码我发现有两行
mCamera.setDisplayOrientation(getPreviewDegree(MainActivity.this));
mCamera.startPreview();
被注释了( MainActivity.java   line 582 583)

把注释去掉之后成功进入app，且成功调用Camera
![screenshot_2017-08-25-19-37-02-804_com dreamwalke](https://user-images.githubusercontent.com/28501741/29712791-3058c1b0-89ce-11e7-9f7d-37574c99d9f5.png)

不过这个app链接好蓝牙设备后，点击照相按钮只是稍微停顿了一下。
应该加一点引导界面或者提示什么的 ，或者弃用照相按钮，由蓝牙串口数据决定照相 ,个人拙见。

------------------------------------------------------------------------------------------------------------------
补充：把注释去掉后 修改MainActivity里的 surfaceChanged
change to:
public void surfaceChanged(SurfaceHolder holder, int format, int width,
                                   int height) {
            //设置参数并开始预览
            Log.d("surfaceChanged", "--------------surfaceChanged------------------");

            int id = getSurfaceId(holder);
            Surface surface = holder.getSurface();

            switch (id) {
                case 1:
                    try {
                        // default layer: circle on left / top
                        int PreviewWidth = 0;
                        int PreviewHeight = 0;
                        WindowManager wm = (WindowManager) getSystemService(Context.WINDOW_SERVICE);//获取窗口的管理器
                        Display display = wm.getDefaultDisplay();//获得窗口里面的屏幕
                        Camera.Parameters parameters  = mCamera.getParameters();
                        // 选择合适的预览尺寸
                        List<Camera.Size> sizeList = parameters.getSupportedPreviewSizes();

                        // 如果sizeList只有一个我们也没有必要做什么了，因为就他一个别无选择
                        if (sizeList.size() > 1) {
                            Iterator<Camera.Size> itor = sizeList.iterator();
                            while (itor.hasNext()) {
                                Camera.Size cur = itor.next();
                                if (cur.width >= PreviewWidth
                                        && cur.height >= PreviewHeight) {
                                    PreviewWidth = cur.width;
                                    PreviewHeight = cur.height;
                                    break;
                                }
                            }
                        }
                        parameters.setPreviewSize(PreviewWidth, PreviewHeight); //获得摄像区域的大小
                        parameters.setPreviewFrameRate(3);//每秒3帧  每秒从摄像头里面获得3个画面
                        parameters.setPictureFormat(PixelFormat.JPEG);//设置照片输出的格式
                        parameters.set("jpeg-quality", 85);//设置照片质量
                        parameters.setPictureSize(PreviewWidth, PreviewHeight);//设置拍出来的屏幕大小
                        //
                        mCamera.setParameters(parameters);//把上面的设置 赋给摄像头
                        mCamera.setPreviewDisplay(holder);//把摄像头获得画面显示在SurfaceView控件里面
                        mCamera.startPreview();//开始预览
                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                    break;
                case 2:
                    // media overlay layer: circle on right / bottom
                    tryDrawing(holder);
                    break;
                default:
                    throw new RuntimeException("wha?");
            }
        };
> 

-------------------------------------------------------------------------------------------------------------------
  但是欢迎引导页调用依然存在问题：MIUI闪退  OPPO正常

**Comment by kali20gakki** [comment]
@mindcont 欢迎引导页面问题已经找到

原因：res下的drawable目录下有图片，drawable下只能放xml。不同系统设定的上限内存不一样，所以有些会崩溃，有些正常。
解决办法： 把drawable目录下的图片全部拖到drawable-hdpi下即可

**Comment by mindcont** [comment]
thanks @kali20gakki , 按照你的办法，我已经更新上去了. #5
